---
- name: Cisco ACI Ansible
  hosts: routers
  gather_facts: false

  tasks:
    - name: Create tenant
      cisco.aci.aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        use_proxy: false
        validate_certs: "{{ validate_certs }}"
        name: AnsibleTest
        descr: tenant by Ansible
        output_path: dump.json
      
    - name: Create vrf 
      cisco.aci.aci_vrf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        use_proxy: false
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"
        state: "present"
      register: vrf_present

  
   
    - name: create BD
      cisco.aci.aci_bd:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        use_proxy: false
        validate_certs: "{{ validate_certs }}"
        name: AnsibleTest_BD1
        vrf: AnsibleTest_VRF
        tenant: AnsibleTest
        state: present
        description: Ansible Test
      register: bd_present