---
- name: ACI Demo Create Tenant
  hosts: aci
  connection: local
  gather_facts: false

  tasks:
    - name: Create ACI Tenant RH_ANSIBLE_TENANT_DEMO
      cisco.aci.aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        tenant: "{{ item.name }}"
        description: "{{ item.desc }}"
        timeout: 600
        state: present
      loop:
        - { name: 00_RH_ANSIBLE_TENANT_DEMO, desc: 00_Tenant_ACI }
        - { name: 01_RH_ANSIBLE_TENANT_DEMO, desc: 01_Tenant_ACI }
