---
- name: ACI Demo create BD bridge domain
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Add Bridge Domain1
      cisco.aci.aci_bd:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        tenant: 00_RH_ANSIBLE_TENANT_DEMO
        bd: "{{ item.bd_name }}"
        mac_address: 00:22:BD:F8:19:FE
        vrf: rh_vrf_demo
        state: present
      delegate_to: localhost
      loop: "{{ jp_tenant_00_bd_list }}"