---
- name: ACI Demo Remove Tenant
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Remove ACI Tenant
      cisco.aci.aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.name }}"
      description: "{{ item.desc }}"
      timeout: 600
      state: absent
      loop:
        - { name: 00_RH_ANSIBLE_TENANT_DEMO, desc: 00_Tenant_ACI }
        - { name: 01_RH_ANSIBLE_TENANT_DEMO, desc: 01_Tenant_ACI }