---
- name: ACI Demo remove VRF
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
    - name: Add a new VRF to a tenant
      cisco.aci.aci_vrf:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        vrf: rh_vrf_demo
        tenant: 00_RH_ANSIBLE_TENANT_DEMO
        descr: rh_vrf_demo
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: absent
      delegate_to: localhost
