---
- name: ACI Demo Create Tenant
  hosts: vpn
  gather_facts: no

  tasks:
   - name: Local command
     ansible.builtin.command: ansible-playbook /home/ansible/git/jp-aci-demo/create_aci_tenant.yml
     become: yes
     become_user: ansible
     args:
        chdir: /home/ansible/git/jp-aci-demo
      