---
- name: ACI Demo Create Tenant via vpn
  hosts: vpn
  connection: local
  gather_facts: no

  tasks:
    - name: Create ACI Tenant RH_ANSIBLE_TENANT_DEMO via VPN
      ansible.builtin.command: pwd
